package dataplane

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"html"
	"io"
	"net"
	"net/http"
	"net/textproto"
	"strings"
	"sync/atomic"
	"time"
)

// popName is the fake point-of-presence reported in X-Amz-Cf-Pop.
const popName = "LOCAL50-C1"

var requestIDSeq atomic.Uint64

// newRequestID generates an X-Amz-Cf-Id-shaped request ID
// (56 base64 characters, like CloudFront's). If crypto/rand fails — which
// should not happen on supported platforms — a time+counter fallback keeps
// the request flowing rather than panicking inside the HTTP handler.
func newRequestID() string {
	b := make([]byte, 42)
	if _, err := rand.Read(b); err != nil {
		binary.BigEndian.PutUint64(b[0:8], uint64(time.Now().UnixNano()))
		binary.BigEndian.PutUint64(b[8:16], requestIDSeq.Add(1))
	}
	return base64.StdEncoding.EncodeToString(b)
}

// hopByHopHeaders are stripped in both directions, per RFC 9110.
var hopByHopHeaders = []string{
	"Connection",
	"Proxy-Connection",
	"Keep-Alive",
	"Proxy-Authenticate",
	"Proxy-Authorization",
	"Te",
	"Trailer",
	"Transfer-Encoding",
	"Upgrade",
}

func copyHeaders(dst, src http.Header) {
	for k, vv := range src {
		for _, v := range vv {
			dst.Add(k, v)
		}
	}
}

func removeHopByHopHeaders(h http.Header) {
	for _, f := range strings.Split(h.Get("Connection"), ",") {
		if f = textproto.TrimString(f); f != "" {
			h.Del(f)
		}
	}
	for _, k := range hopByHopHeaders {
		h.Del(k)
	}
}

// appendXForwardedFor sets X-Forwarded-For to the viewer's prior value (if any)
// with the viewer IP appended. CloudFront always does this, independent of the
// cache / origin request policy, so prior comes from the original viewer
// request rather than the policy-filtered header set.
func appendXForwardedFor(h http.Header, prior, remoteAddr string) {
	ip, _, err := net.SplitHostPort(remoteAddr)
	if err != nil {
		ip = remoteAddr
	}
	if prior != "" {
		ip = prior + ", " + ip
	}
	h.Set("X-Forwarded-For", ip)
}

func addVia(h http.Header, domain string) {
	via := "1.1 " + domain + " (CloudFront)"
	if existing := h.Get("Via"); existing != "" {
		via = existing + ", " + via
	}
	h.Set("Via", via)
}

// writeCFError renders an error page shaped like CloudFront's
// "The request could not be satisfied" responses.
func writeCFError(w http.ResponseWriter, status int, requestID, message string) {
	body, header := cfErrorPage(status, requestID, message)
	for k, vv := range header {
		w.Header()[k] = vv
	}
	w.WriteHeader(status)
	_, _ = io.Copy(w, body)
}

// cfErrorPage builds the body and headers of a CloudFront-shaped error page so
// it can either be written directly or flow through the response pipeline.
func cfErrorPage(status int, requestID, message string) (io.ReadCloser, http.Header) {
	header := http.Header{}
	header.Set("Content-Type", "text/html")
	header.Set("Server", "CloudFront")
	header.Set("X-Cache", "Error from localfront")
	header.Set("X-Amz-Cf-Id", requestID)
	body := fmt.Sprintf(`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>%d ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
%s
<BR clear="all">
We can't connect to the server for this app or website at this time. This is emulated by localfront.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by localfront (CloudFront emulator)
Request ID: %s
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
`, status, html.EscapeString(message), html.EscapeString(requestID))
	return io.NopCloser(strings.NewReader(body)), header
}
