package dataplane

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"html"
	"net"
	"net/http"
	"net/textproto"
	"strings"
)

// popName is the fake point-of-presence reported in X-Amz-Cf-Pop.
const popName = "LOCAL50-C1"

// newRequestID generates an X-Amz-Cf-Id-shaped request ID
// (56 base64 characters, like CloudFront's).
func newRequestID() string {
	b := make([]byte, 42)
	if _, err := rand.Read(b); err != nil {
		panic(err) // crypto/rand never fails on supported platforms
	}
	return base64.StdEncoding.EncodeToString(b)
}

// hopByHopHeaders are stripped in both directions, per RFC 9110.
var hopByHopHeaders = []string{
	"Connection",
	"Proxy-Connection",
	"Keep-Alive",
	"Proxy-Authenticate",
	"Proxy-Authorization",
	"Te",
	"Trailer",
	"Transfer-Encoding",
	"Upgrade",
}

func copyHeaders(dst, src http.Header) {
	for k, vv := range src {
		for _, v := range vv {
			dst.Add(k, v)
		}
	}
}

func removeHopByHopHeaders(h http.Header) {
	for _, f := range strings.Split(h.Get("Connection"), ",") {
		if f = textproto.TrimString(f); f != "" {
			h.Del(f)
		}
	}
	for _, k := range hopByHopHeaders {
		h.Del(k)
	}
}

func appendXForwardedFor(h http.Header, remoteAddr string) {
	ip, _, err := net.SplitHostPort(remoteAddr)
	if err != nil {
		ip = remoteAddr
	}
	if prior := h.Get("X-Forwarded-For"); prior != "" {
		ip = prior + ", " + ip
	}
	h.Set("X-Forwarded-For", ip)
}

func addVia(h http.Header, domain string) {
	via := "1.1 " + domain + " (CloudFront)"
	if existing := h.Get("Via"); existing != "" {
		via = existing + ", " + via
	}
	h.Set("Via", via)
}

// writeCFError renders an error page shaped like CloudFront's
// "The request could not be satisfied" responses.
func writeCFError(w http.ResponseWriter, status int, requestID, message string) {
	w.Header().Set("Content-Type", "text/html")
	w.Header().Set("Server", "CloudFront")
	w.Header().Set("X-Cache", "Error from localfront")
	w.Header().Set("X-Amz-Cf-Id", requestID)
	w.WriteHeader(status)
	fmt.Fprintf(w, `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>%d ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
%s
<BR clear="all">
We can't connect to the server for this app or website at this time. This is emulated by localfront.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by localfront (CloudFront emulator)
Request ID: %s
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
`, status, html.EscapeString(message), html.EscapeString(requestID))
}
